#ifndef PARAMETERS_H
#define PARAMETERS_H
#include "Arduino.h"

#define NB_SONARS 5

#define SONAR_ECHO_FRONT_L SONAR_0_ECHO
#define SONAR_TRIG_FRONT_L SONAR_0_TRIG
#define SONAR_ECHO_FRONT_R SONAR_5_ECHO
#define SONAR_TRIG_FRONT_R SONAR_5_TRIG
#define SONAR_ECHO_BACK_L SONAR_2_ECHO
#define SONAR_TRIG_BACK_L SONAR_2_TRIG
#define SONAR_ECHO_BACK_R SONAR_4_ECHO
#define SONAR_TRIG_BACK_R SONAR_4_TRIG

//#define SONAR_ECHO_R       SONAR_5_ECHO
//#define SONAR_TRIG_R       SONAR_5_TRIG

#endif